[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# These headers ensure proper MIME types for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Proxy rule for n8n webhooks
[[redirects]]
  from = "/webhook/*"
  to = "https://n8n.artbachmann.eu/webhook/:splat"
  status = 200
  force = true

# Proxy rule for Camera n8n webhooks
[[redirects]]
  from = "/webhook-camera/*"
  to = "https://n8n.artbachmann.eu/webhook/:splat"
  status = 200
  force = true

# Ensure all routes go to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
